CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authors VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(19,2) NOT NULL,
    published_on DATE NOT NULL,
    publisher VARCHAR(255) NOT NULL,
    category_id BIGINT,
    stock INT DEFAULT 0,
    image_url VARCHAR(255),
    CONSTRAINT fk_books_category FOREIGN KEY (category_id) REFERENCES categories(id)
);




    
create table customers (
	id bigint generated by default as identity,
	city varchar(60) not null,
	country_region varchar(55) not null,
	email varchar(254) not null,
	name varchar(50) not null,
	phone_number varchar(15) not null,
	postal_code varchar(18) not null,
	street_and_house_number varchar(100) not null,
	surname varchar(50) not null,
	primary key (id)
);
    
create table orders (
	id bigint generated by default as identity,
	order_date date not null,
	book_id bigint,
	customer_id bigint,
	primary key (id)
);

CREATE TABLE USERS (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	password VARCHAR(255) NOT NULL,
	enabled TINYINT(1) NOT NULL,
	PRIMARY KEY (username)
);

CREATE TABLE AUTHORITIES (
	username VARCHAR(255) NOT NULL,
	authority VARCHAR(255) NOT NULL
);